### ISSUE TITLE
Change default local folder

### ISSUE THREAD

**Issue by leschek** [sheychen290/encryptedNextcloudPortableClient#2]
When you run it first time it offers default local folder C:\Users\name\Nextcloud. I think it should be changed, if possible, to folder inside of its own installation folder.

**Comment by sheychen290** [comment]
It seems impossible.

Folder path is set in nextcloud.cfg
```0\Folders\1\localPath=[...]``` 
but is overrided during first setup.

Sorry

**Comment by sheychen290** [comment]
An idea should be to create nextcloud.cfg on first start from cmd
and them skip nextcloud setup.

**Comment by sheychen290** [comment]
Fix in v0.2
